modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="desafosahuaria"
version="1.8.0"
displayName="DesafíoSahuaria+"
credits="Hecho por: ElPerches"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="ElPerches, MCreator"
description="Complemento Desafío Anexo Sahuaripa"

[[dependencies.desafosahuaria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




